export { ReactComponent as ArrowLeft } from './arrow-left.svg';
export { ReactComponent as ArrowRight } from './arrow-right.svg';
export { ReactComponent as Close } from './close.svg';
export { ReactComponent as Facebook } from './facebook.svg';
export { ReactComponent as Instagram } from './instagram.svg';
export { ReactComponent as Menu } from './menu.svg';
export { ReactComponent as Right } from './right.svg';
export { ReactComponent as Search } from './search.svg';
export { ReactComponent as Twitter } from './twitter.svg';